export const FETCH_BARBERS = 'FETCH_BARBERS';
export const FETCH_TIME_APPOINTMENT = 'FETCH_TIME_APPOINTMENT';
export const SET_DATE_APPOINTMENT = 'SET_DATE_APPOINTMENT';
export const SET_BARBER_APPOINTMENT = 'SET_BARBER_APPOINTMENT';
export const SET_TIME_APPOINTMENT = 'SET_TIME_APPOINTMENT';
export const SET_SERVICE_APPOINTMENT = 'SET_SERVICE_APPOINTMENT';
